# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-14 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couses',
            new_name='Course',
        ),
    ]
